### ISSUE TITLE
ICS event subscription

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojo/community-platform#1246]
I am building a calendar based on the events. I would like to subscribe to the events via an ICS link.
I think, this is [not yet implemented](https://github.com/CoderDojo/community-platform/search?q=ICS&type=Issues).

How would one go about it to implement this? Which parts of the code should be touched?

Another place would be to use an external service. The API already exports enought information about the events so that an external service would suffice. If the external service is a node service, this makes is easier to integrate the code later.

Which way would you prefer?

**Comment by Wardormeur** [comment]
Hey Nicco
There are a couple of PR to work on this already, the main issue being timezone: without it, the ICS will be invalid. So the main requirement before that is to be able to save the timezone of the event, and the only source we use (which isn't reliable)  is the creator's one (the champion, when saving the event); and considering we were regarding the rework of event creation, I delayed the change. Another way would be to use the event's location, which means mapping the address to it's region's timezone.
I would prefer an internal service (but this haven't been really discussed), simply because it allows us to make use of it from the emails easily (without storing a reference as we can reuse the eventId) and purge the images when we wishes to.
Existing work on it : 
https://github.com/Wardormeur/ics-to-s3
https://github.com/CoderDojo/cp-zen-platform/pull/1258
Changes for the cp-local-development's docker-compose:
```
  s3:
    image: andrewgaul/s3proxy
    entrypoint: 
      - sh
      - -c
      - "{ sleep 5 && echo -e \"PUT http://localhost:80/zenbookingqrcode HTTP/1.0\\n\\n\" | nc localhost 80; } & sh /opt/s3proxy/run-docker-container.sh"
    environment:
      - S3PROXY_AUTHORIZATION=none
    ports:
      - 8099:80
  ics:
    image: node:carbon
    command: yarn dev
    working_dir: /usr/src/app
    volumes:
      - ./workspace-zen/services/ics-generator:/usr/src/app:Z
```
If you wish to extend my PR, feel free to, or you can build your own :)
I'll be happy to help in both cases
